library('shiny')
library('shinyBS')

shinyUI(navbarPage(
    title = 'recount2: analysis-ready RNA-seq gene and exon counts datasets',
    tabPanel('Datasets',
        tags$head(
            includeScript("google-analytics.js"),
            tags$script(src = 'highlight.pack.js'),
            tags$script(src = 'shiny-showcase.js'),
            tags$link(rel = "stylesheet", type = "text/css",
                href = "rstudio.css")
        ),
        bsAlert('annotationalert'),
        HTML('<a href="https://github.com/leekgroup/recount-website" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'github-recount-web\', 1)">'), img(src='https://raw.githubusercontent.com/leekgroup/recount-website/master/website/recount.png', align = "left", 'style' = 'padding-right:18px'), HTML('</a>'),
        h3('A multi-experiment resource of analysis-ready RNA-seq gene and exon count datasets'),
        p(strong('recount2'), ' is an online resource consisting of RNA-seq gene and exon counts as well as coverage bigWig files for 2041 different studies. It is the second generation of the ', HTML('<a href="http://bowtie-bio.sourceforge.net/recount/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'recount-old\', 1)">ReCount project</a>.'), ' The raw sequencing data were processed with ', HTML('<a href="http://rail.bio" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'rail-rna\', 1)">Rail-RNA</a>'), ' as described at ', HTML('<a href="http://biorxiv.org/content/early/2016/01/29/038224" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'paper-rail\', 1)">bioRxiv 038224</a>'), ' which created the coverage bigWig files. For ease of statistical analysis, for each study we created count tables at the gene and exon levels and extracted phenotype data, which we provide in their raw formats as well as in RangedSummarizedExperiment R objects (described in the ', HTML('<a href="http://bioconductor.org/packages/SummarizedExperiment" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-SE\', 1)">SummarizedExperiment</a>'), ' Bioconductor package). We also computed the mean coverage per study and provide it in a bigWig file, which can be used with the ', HTML('<a href="http://bioconductor.org/packages/derfinder" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-derfinder\', 1)">derfinder</a>'), ' Bioconductor package to perform annotation-agnostic differential expression analysis at the expressed regions-level as described at ', HTML('<a href="http://biorxiv.org/content/early/2015/02/19/015370" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'paper-derfinder\', 1)">bioRxiv 015370</a>.'), ' The count tables, RangedSummarizeExperiment objects, phenotype tables, sample bigWigs, mean bigWigs, and file information tables are ready to use and freely available here. We also created the ',  HTML('<a href="http://bioconductor.org/packages/recount" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-recount\', 1)">recount</a>'), ' Bioconductor package which allows you to search and download the data for a specific study . By taking care of several preprocessing steps and combining many datasets into one easily-accessible website, we make finding and analyzing RNA-seq data considerably more straightforward.'),
        tags$hr(),
        h3('Related publications'),
        HTML('<b>Collado-Torres L</b>, <b>Nellore A</b>, Kammers K, Ellis SE, Taub MA, Hansen KD, Jaffe AE, Langmead B, Leek JT. <a href="http://biorxiv.org/content/early/2016/08/08/068478" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'recount-biorxiv\', 1)">recount: A large-scale resource of analysis-ready RNA-seq expression data</a>. <i>bioRxiv</i> <b>068478</b>.'),
        tags$hr(),
        h3('The Datasets'),
        DT::dataTableOutput('metadata'),
        tags$hr(),
        downloadButton('downloadData', 'Download list of studies matching search results'),
        helpText('Note that GTEx is separated from this list.'),
        tags$hr(),
        h3('Authors'),
        tags$ul(
            tags$li(HTML('<a href="http://lcolladotor.github.io/about.html" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'about-leo\', 1)">Leonardo Collado-Torres</a>')),
            tags$li(HTML('<a href="http://nellore.bio/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'about-abhi\', 1)">Abhinav Nellore</a>')),
			tags$li(HTML('<a href="http://www.biostat.jhsph.edu/~kkammers/index.html" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'about-kai\', 1)">Kai Kammers</a>')),
			tags$li(HTML('<a href="http://jtleek.com/people/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'about-shannon\', 1)">Shannon E Ellis</a>')),
			tags$li(HTML('<a href="http://biostat.jhsph.edu/~mtaub/About.html" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'about-margaret\', 1)">Margaret A Taub</a>')),
			tags$li(HTML('<a href="http://www.hansenlab.org/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'about-kasper\', 1)">Kasper D Hansen</a>')),
			tags$li(HTML('<a href="http://aejaffe.com/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'about-andrew\', 1)">Andrew E Jaffe</a>')),
            tags$li(HTML('<a href="http://www.cs.jhu.edu/~langmea/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'about-ben\', 1)">Ben Langmead</a>')),
            tags$li(HTML('<a href="http://jtleek.com/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'about-jeff\', 1)">Jeff Leek</a>'))
        ),
        tags$hr(),
        h3('Support'),
        p('If you need help with the ', HTML('<a href="http://bioconductor.org/packages/recount" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-recount\', 1)">recount</a>'), ' Bioconductor package please get in touch via the ', HTML('<a href="https://support.bioconductor.org/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-support\', 1)">Bioconductor support website</a>'), '(remember to use the ', strong('recount'), ' tag) or via the ', HTML('<a href="https://github.com/leekgroup/recount/issues" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'issues-recount\', 1)">recount Bioconductor package repository</a>.'), ' For support on reproducing the recount2 project, please get in touch via the ', HTML('<a href="https://github.com/leekgroup/recount-website/issues" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'issues-recount-web\', 1)">recount-website repository</a>.'))
    ),
    tabPanel('Popular datasets',
        DT::dataTableOutput('popular')
    ),
    tabPanel('GTEx',
        p('This tab shows the information for the GTEx project. Due to its size, we also provide ranged summarized experiment objects (RSE) by tissue at the gene and exon levels.'),
        DT::dataTableOutput('gtex')
    ),
    tabPanel('TCGA',
        p('This tab shows the information for the TCGA project. Due to its size, we also provide ranged summarized experiment objects (RSE) by tissue at the gene and exon levels.'),
        DT::dataTableOutput('tcga')
    ),
    tabPanel('Documentation',
        h3('recount2 objects documentation'),
        p('All columns of the table below are sortable and searchable. The columns are as follows:'),
        h5('accession'),
        p('The SRA accession identifier for the study. The link points to SRA for a full description of the study.'),
        h5('number of samples'),
        p('The total number of samples available for the given study. Note that in some exceptional cases not all samples for a given study were analyzed with ', HTML('<a href="http://rail.bio" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'rail-rna\', 1)">Rail-RNA</a>.')),
        h5('species'),
        p('The species of the samples under study.'),
        h5('abstract'),
        p('The abstract describing the study as provided by SRA via the ', HTML('<a href="http://bioconductor.org/packages/SRAdb" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-SRAdb\', 1)">SRAdb</a>'), ' Bioconductor package.'),
        h5('RSE gene'),
        p('The RangedSummarizedExperiment object for the counts summarized at the gene level using the Gencode v25 (GRCh38.p7, CHR) annotation as provided by ', HTML('<a href="https://www.gencodegenes.org/releases/25.html" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'gencode\', 1)">Gencode</a>. Note that the GRanges object recount::recount_genes includes bp_length as a metadata column which is the sum of the exon widths. If two exons are overlapping, the overlapped bases are only counted once.')),
        h5('counts gene'),
        p('A tsv file with the count matrix used to create the RangedSummarizedExperiment object at the gene level.'),
        h5('RSE exon'),
        p('The RangedSummarizedExperiment object for the counts summarized at the exon level using the Gencode v25 (GRCh38.p7, CHR) annotation as provided by ', HTML('<a href="https://www.gencodegenes.org/releases/25.html" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'gencode\', 1)">gencode</a>. This GRangesList object recount::recount_exons has 1 element per gene. For each gene this object contains the reduced exons such that they are non-overlapping within a gene.')),
        h5('counts exon'),
        p('A tsv file with the count matrix used to create the RangedSummarizedExperiment object at the exon level.'),
        h5('RSE junctions'),
        p('The RangedSummarizedExperiment object for the counts summarized at the junction level. This GRanges object has 1 element per junction. For each junction this object contains the transcript names for the Gencode v24 junctions, transcript names and gene ids matching those used in the RSE objects at the gene or exon levels (based on Gencode v25 CHR regions), junction class, proposed gene ids and symbols. The junction ids match those used in the jx_cov and jx_bed files explained below. This file is present only if the project has at least one junction detected.'),
        h5('counts jx'),
        p('A tsv file with the count matrix used to create the RangedSummarizedExperiment object at the junction level. This file is present only if the project has at least one junction detected.'),
        h5('Junction raw coverage file'),
        HTML('The link jx_cov points to the raw junction coverage file that contains the junction ids (comma-separated), the sample ids (comma-separated), and the actual coverage value for the junction. Sample ids can be matched to run and project accession numbers using <a href="https://jhubiostatistics.shinyapps.io/recount/sample_ids.tsv" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'sample-ids\', 1)">sample_ids.tsv</a> (junction id, project accession, run accession).'),
        h5('Junction BED file'),
        p('The link jx_bed points to the BED file with one entry per junction present in the given project. The name of the junction includes the junction id, the donor, acceptor, and overall (if present in both) transcript names based on Gencode v24.'),
        h5('phenotype'),
        p('The phenotype information (sample metadata) in a tsv file used for both RangedSummarizedExperiment objects. The table includes the SRA study id, the SRA sample id, the SRA experiment id, the SRA run id, the reads counts as reported by SRA, the number of reads aligned by Rail-RNA, the proportion of reads reported by SRA that aligned, whether the sample was paired-end or not, whether we think SRA misreported the paired-end label, the number of mapped read count by Rail-RNA, the coverage AUC, the ', HTML('<a href="http://www.cs.cmu.edu/~ckingsf/sharq/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'sharq\', 1)">SHARQ prototype</a>'), ' tissue, the ', HTML('<a href="http://www.cs.cmu.edu/~ckingsf/sharq/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'sharq\', 1)">SHARQ prototype</a>'), ' cell type, the biosample sumbmission date, the biosample publication date, the biosample update date, the average read length, the GEO accession id, the sample title as extracted from GEO, the sample characteristics as extracted from GEO, and the name of the coverage bigWig file.'),
        h5('files info'),
        p('A tsv file with the names of the uploaded files, the md5sum, the size in bytes and the url to download the actual files.'),
        h5('Annotation used'),
        p('The Gencode v25 GFF3 file with the comprehensive gene annotation (CHR regions) is available at the ', HTML('<a href="https://www.gencodegenes.org/releases/25.html" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'gencode\', 1)">Gencode website</a>.')),
        tags$hr(),
        h3('Getting started with RangedSummarizedExperiment objects'),
        p('Check out the ', HTML('<a href="http://bioconductor.org/packages/recount" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-recount\', 1)">recount</a>'), ' Bioconductor package for how to download data from the recount2 project and get started with your own analysis. The ', HTML('<a href="http://leekgroup.github.io/recount/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'vignette-recount\', 1)">quick start vignette</a>'), ' is particularly helpful. For more details check the ', HTML('<a href="http://bioconductor.org/packages/SummarizedExperiment" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-SE\', 1)">SummarizedExperiment</a>'), ' Bioconductor package for an overview on RangedSummarizedExperiment objects. Most RNA-seq differential expression Bioconductor packages use them. In particular, the vignette of the ', HTML('<a href="http://bioconductor.org/packages/DESeq2" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-DESeq2\', 1)">DESeq2</a>'), ' Bioconductor package shows in detail how to perform an analysis with them. You might also want to use the ', HTML('<a href="http://bioconductor.org/packages/DEFormats" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-DEFormats\', 1)">DEFormats</a>'), ' Bioconductor package for converting these objects to other formats.'),
        h3('Code used'),
        HTML('The code for analyzing the <a href="http://rail.bio" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'rail-rna\', 1)">Rail-RNA</a> output and creating this website is available via <a href="https://github.com/leekgroup/recount-website" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'github-recount-web\', 1)">GitHub</a>.'),
        tags$hr(),
        h3('Known issues'),
        tags$li('Rail-RNA run on SRA data'),
        HTML('Check the <a href="https://github.com/nellore/runs/blob/master/sra/v2/hg38/NOTES">NOTES</a> on the Rail-RNA run on SRA data (version 2) which describes why some samples were discarded.'),
        tags$li('Single-cell studies with pooled samples'),
        HTML('Some single-cell studies like SRP058046 sequenced more than one single-cell but are available only as a pooled sample from the Sequence Read Archive. Currently these studies might not be useful for differential expression analysis via recount2 but can be used for checking if a given exon-exon junction is present or if a given region is expressed. Reported by <a href="https://www.helmholtz-muenchen.de/icb/">Lukas Simon</a>.'),
        h5('Found an issue?'),
        HTML('If you found an issue with recount2, please email us or describe the problem at the <a href="https://github.com/leekgroup/recount-website/issues">recount-website issue tracker</a>. Thank you!')
    ),
    tabPanel('Download data with R',
        p('The following R code shows how to use the', HTML('<a href="http://bioconductor.org/packages/recount" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'bioc-recount\', 1)">recount</a>'), 'Bioconductor package for downloading data. In this example we will download the data for study SRP009615.'),
        includeMarkdown('download.md')
    ),
    tabPanel('Accessing recount2 via SciServer',
        HTML('Not everyone has over 8 terabytes of disk space available to download all the data from the recount2 project. However, thanks to <a href="http://www.sciserver.org/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'idies\', 1)">SciServer</a> you can access it locally via a Jupyter Notebook. If you do so and want to share your work, please let the <a href="http://www.sciserver.org/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'idies\', 1)">SciServer</a> maintainers know via Twitter at <a href="https://twitter.com/IDIESJHU" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'twitter-idies\', 1)">IDIESJHU</a>. The step by step instructions describing how to access recount2 via <a href="http://www.sciserver.org/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'idies\', 1)">SciServer</a> are available in the <a href="http://bioconductor.org/packages/release/bioc/vignettes/recount/inst/doc/recount-quickstart.html#accessing-recount-via-sciserver" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'vignette-recount\', 1)">recount vignette</a>.'),
        p(HTML('<a href="http://bioconductor.org/packages/release/bioc/vignettes/recount/inst/doc/recount-quickstart.html#accessing-recount-via-sciserver" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'vignette-recount\', 1)"><img src="https://raw.githubusercontent.com/leekgroup/recount-website/master/sciserver_demo/demo1.png" align="center"/></a>'))
    ),
    tabPanel('Contribute your data',
        h3('Contribute your data to recount2!'),
        HTML('If you are interested in contributing your human RNA-seq data sequenced on the Illumina platform to recount2, please check how to do so at <a href="https://github.com/leekgroup/recount-contributions">recount-contributions</a>. Thank you!')
    ),
    tags$hr(),
    p('This research was supported by NIH R01 GM105705. LCT was supported by Consejo Nacional de Ciencia y Tecnología México 351535. LCT and AEJ were supported by NIH 1R21MH109956-01. Amazon Web Services experiments were supported by AWS in Education research grants. Storage costs on S3 for TCGA runs were partially covered by a grant from Seven Bridges Genomics for use of the Cancer Genomics Cloud.'),
	p(strong('recount2'), ' is hosted on ', HTML('<a href="http://www.sciserver.org" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'sciserver\', 1)">SciServer</a>,'), 'a collaborative research environment for large-scale data-driven science. It is being developed at, and administered by, the ', HTML('<a href="http://idies.jhu.edu/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'idies\', 1)">Institute for Data Intensive Engineering and Science (IDIES)</a>'), ' at Johns Hopkins University. SciServer is funded by the National Science Foundation Award ACI-1261715.'),
    p(HTML('<a href="http://idies.jhu.edu/" onclick="ga(\'send\', \'event\', \'click\', \'link\', \'idies\', 1)"><img src="http://idies.jhu.edu/wp-content/themes/idies/assets/img/idieslogo.png" align="right"/></a>')),
    tags$br(),
    tags$br(),
    tags$br(),
    tags$br()
))